savedir: checkpoints/randomforest_default/
model: RandomForestRegressor
scoring:
  r2: r2
  neg_mean_absolute_error: neg_mean_absolute_error
refit: r2
independent_variables:
- weekday
- month
- weathercode
- temperature_2m_mean
- apparent_temperature_min
- apparent_temperature_max
- sunshine_duration
- uv_index_max
- et0_fao_evapotranspiration
- rain_sum
- precipitation_hours
- cloud_cover_max
- windspeed_10m_max
- windgusts_10m_max
grid_params:
  n_estimators:
  - 75
  - 100
  - 200
  - 300
  max_depth:
  - 5
  - 6
  - 7
  - 8
  max_features:
  - 0.5
  - 0.75
  - 1
  min_samples_leaf:
  - 1
  - 2
  - 3
  - 5
log:
  pale_ale:
    best_params:
      max_depth: 5
      max_features: 0.75
      min_samples_leaf: 5
      n_estimators: 100
    scores:
      r2:
        train: 0.6342821073523861
        val: 0.40507793933200953
      neg_mean_absolute_error:
        train: -1.1708902491180535
        val: -1.4945687191762658
  lager:
    best_params:
      max_depth: 6
      max_features: 0.75
      min_samples_leaf: 2
      n_estimators: 100
    scores:
      r2:
        train: 0.8216774551532051
        val: 0.5185369858073929
      neg_mean_absolute_error:
        train: -0.9233688225895037
        val: -1.5128472002634936
  ipa:
    best_params:
      max_depth: 7
      max_features: 0.75
      min_samples_leaf: 1
      n_estimators: 100
    scores:
      r2:
        train: 0.823787088848559
        val: 0.41567305129292775
      neg_mean_absolute_error:
        train: -0.6342470722899354
        val: -1.1476022662138479
  white_beer:
    best_params:
      max_depth: 6
      max_features: 0.75
      min_samples_leaf: 2
      n_estimators: 300
    scores:
      r2:
        train: 0.808631449296365
        val: 0.46528420377032526
      neg_mean_absolute_error:
        train: -0.6442773941912215
        val: -1.0608642948939238
  dark_beer:
    best_params:
      max_depth: 7
      max_features: 0.5
      min_samples_leaf: 5
      n_estimators: 100
    scores:
      r2:
        train: 0.6760213667920087
        val: 0.3877010869192229
      neg_mean_absolute_error:
        train: -0.7380421779535646
        val: -0.9983798767127992
  fruit_beer:
    best_params:
      max_depth: 7
      max_features: 0.75
      min_samples_leaf: 5
      n_estimators: 100
    scores:
      r2:
        train: 0.5735788720672781
        val: 0.18257955623453026
      neg_mean_absolute_error:
        train: -0.9407141429970066
        val: -1.335238927583706
