savedir: checkpoints/randomforest_default/
model: RandomForestRegressor
independent_variables:
- weekday
- month
- weathercode
- temperature_2m_mean
- apparent_temperature_min
- apparent_temperature_max
- sunshine_duration
- uv_index_max
- et0_fao_evapotranspiration
- rain_sum
- precipitation_hours
- cloud_cover_max
- windspeed_10m_max
- windgusts_10m_max
grid_params:
  n_estimators:
  - 75
  - 100
  - 200
  - 300
  max_depth:
  - 5
  - 6
  - 7
  - 8
  max_features:
  - 0.5
  - 0.75
  - 1
  min_samples_leaf:
  - 1
  - 2
  - 3
  - 5
