savedir: checkpoints/randomforest_default/
model: RandomForestRegressor
scoring:
  r2: r2
  neg_mean_absolute_error: neg_mean_absolute_error
refit: r2
independent_variables:
- weekday
- month
- weathercode
- temperature_2m_mean
- apparent_temperature_min
- apparent_temperature_max
- relative_humidity_2m_mean
- sunshine_duration
- uv_index_max
- et0_fao_evapotranspiration
- rain_sum
- precipitation_hours
- cloud_cover_max
- windspeed_10m_max
- windgusts_10m_max
grid_params:
  n_estimators:
  - 75
  - 100
  - 200
  - 300
  max_depth:
  - 5
  - 6
  - 7
  - 8
  max_features:
  - 0.5
  - 0.75
  - 1
  min_samples_leaf:
  - 1
  - 2
  - 3
  - 5
log:
  pale_ale:
    best_params:
      max_depth: 5
      max_features: 0.5
      min_samples_leaf: 1
      n_estimators: 100
    scores:
      r2:
        train: 0.7064444823466721
        val: 0.40759248491160277
      neg_mean_absolute_error:
        train: -1.0792029347643335
        val: -1.4908334157154188
  lager:
    best_params:
      max_depth: 8
      max_features: 0.75
      min_samples_leaf: 3
      n_estimators: 300
    scores:
      r2:
        train: 0.8380001133365967
        val: 0.5176731644999629
      neg_mean_absolute_error:
        train: -0.8526505152864152
        val: -1.5005377350740283
  ipa:
    best_params:
      max_depth: 6
      max_features: 0.75
      min_samples_leaf: 1
      n_estimators: 100
    scores:
      r2:
        train: 0.7824580909817213
        val: 0.40929385655108613
      neg_mean_absolute_error:
        train: -0.7043828532677584
        val: -1.1521962122110467
  white_beer:
    best_params:
      max_depth: 7
      max_features: 0.75
      min_samples_leaf: 2
      n_estimators: 300
    scores:
      r2:
        train: 0.8416983873319752
        val: 0.46016328115963284
      neg_mean_absolute_error:
        train: -0.5757963908739872
        val: -1.0691563774014026
  dark_beer:
    best_params:
      max_depth: 7
      max_features: 0.75
      min_samples_leaf: 3
      n_estimators: 100
    scores:
      r2:
        train: 0.772574444046118
        val: 0.3875335720301794
      neg_mean_absolute_error:
        train: -0.6211813656893435
        val: -0.9937792189725148
  fruit_beer:
    best_params:
      max_depth: 8
      max_features: 0.5
      min_samples_leaf: 3
      n_estimators: 75
    scores:
      r2:
        train: 0.6799786596354411
        val: 0.18512143562949895
      neg_mean_absolute_error:
        train: -0.8138414582924213
        val: -1.345538258823705
