savedir: checkpoints/catboost_default2/
model: CatBoostRegressor
independent_variables:
- weekday
- month
- weathercode
- temperature_2m_mean
- apparent_temperature_min
- apparent_temperature_max
- sunshine_duration
- uv_index_max
- et0_fao_evapotranspiration
- rain_sum
- precipitation_hours
- cloud_cover_max
- windspeed_10m_max
- windgusts_10m_max
grid_params:
  depth:
  - 3
  - 4
  - 5
  learning_rate:
  - 0.05
  - 0.1
  - 0.25
  iterations:
  - 75
  - 100
  - 200
  l2_leaf_reg:
  - 3
  - 5
  - 10
  subsample:
  - 0.5
  - 0.75
  - 1
  early_stopping_rounds:
  - 50
